### ISSUE TITLE
Scopes not being colorized in default vscode themes

### ISSUE THREAD

**Issue by gravejester** [PowerShell/EditorSyntax#5] opened 2016-06-01 17:50 UTC
There are a number of scopes that we use in the PowerShell syntax highlighting definitions that are not currently colorized in the default themes in Visual Studio Code.

For instance:
- constant.other
- constant.character.escape (used for escape characters in strings)
- keyword.operator (used for all operators)
- support (used for all commands; verb-noun as well as aliases)

Should we try to get some colors for these into the default themes? Or should we create our own PowerShell optimized versions of the default themes? I'm mainly thinking about the default light+ and dark+ themes.

I'd rather not use the "wrong" scope names just to get colors. This will only mess things up when you change to other themes.

**Comment by daviwil** [comment] 2016-06-01 18:09
I'd prefer to stick with the right scope names and potentially make pull requests to VS Code's default themes if we can improve them for all languages.  It'd be difficult to point people to PowerShell-specific versions of the default themes so I'd like to do things in the "official" way as much as possible.

I can help you get a PR through to VS Code if you can figure out a good way to light up these scopes correctly in their default themes.  Showing some comparison with Sublime Text's highlighting for those scopes would also be helpful in convincing them to accept a PR.

**Comment by gravejester** [comment] 2016-06-01 18:20
Ok. I can play around with the default themes a bit and paste some screenshots here for discussion. And when (if) we think we have found something that works, we can create a PR to try to get the default themes updated :)

**Comment by daviwil** [comment] 2016-06-01 18:25
Sounds like a good plan!

**Comment by gerane** [comment] 2016-07-02 01:59
Btw, @gravejester @daviwill, I have over 280 themes on the vscode gallery 

https://github.com/gerane/VSCodeThemes

I can try to start adding support for these, but might take me a while. I am always open for pull requests on them. 

When code first came out, there were like 10 themes, and I'm a huge fan of editor customization and expansion, and I wasn't a big fan of the default themes. I had experience working with atom themes and porting those, so I scripted porting almost 300 themes.

I might need to see what a few of these look like so I know what I'm adding.

**Comment by gerane** [comment] 2016-07-02 02:01
Btw, I have a few insights on where VS Code themes fall short or don't look right compared to sublime.

**Comment by gerane** [comment] 2016-07-02 02:01
Selected line highlight has given me huge headaches for example.

**Comment by omniomi** [comment] 2018-05-21 20:40
Closing as a duplicate of #8 and because a number of the scopes have been changed since this was opened. @gravejester we should start a new discussion on scope names.

**Closed by omniomi** 2018-05-21 20:40 UTC
Labels: enhancement
