### ISSUE TITLE
its possible to implement empty coallesing operator

### ISSUE THREAD

**Issue by p0W3RH311** [PowerShell/EditorSyntax#193] opened 2020-01-11 16:51 UTC

**Comment by TylerLeonhardt** [comment] 2020-01-13 15:32
Can you elaborate please?

**Comment by michaelblyons** [comment] 2020-01-23 19:20
Likely duplicate of #185?

**Comment by TylerLeonhardt** [comment] 2020-01-23 20:34
Yeah I think that's what this is. I'm gonna close it as a dupe of #185

**Closed** 2020-01-23 20:34 UTC
Labels: duplicate
