### ISSUE TITLE
Variables in a string followed by a ? do not highlight the ? as part of the variable in VS Code

### ISSUE THREAD

**Issue by scrthq** [PowerShell/EditorSyntax#40] opened 2017-03-12 08:50 UTC
Working on some API call wrapper functions for the first time in Visual Studio Code and I noticed that question marks immediately following a variable are not highlighted as part of the variable. In ISE, it's easy to catch because the question mark will highlight orange and needs to be escaped to be not be considered part of the variable. In VSCode, there's no marker.

Example:

`"https://www.googleapis.com/drive/v3/teamdrives/$TeamDriveID?fields=capabilities%2Cid%2Ckind%2Cname"`

In ISE, the `?fields` after `$TeamDriveID` will be included in the variable, renaming the variable to `$TeamDriveID?fields` and causing it to fail. In VS Code, there's no indicator via Syntax Highlighting that that extra bit is being included.

**Comment by omniomi** [comment] 2018-05-21 20:30
This is a duplicate of #49.

**Closed by omniomi** 2018-05-21 20:30 UTC
Labels: bug
